### ISSUE TITLE
Using RNA-seq

### ISSUE THREAD

**Issue by MaryGoAround** [AngelCampos/Pathifier-Tool-Kit#3]
Sorry can I use your software Pathifier for RNA-seq? If yes, should I use raw read counts, normalized or RPKM values?

Thank you much for any information

I have used normalised values from DESeq2 on my RNA-seq data but I get this error

```
> min_exp <- quantile(as.vector(exp.matrix), 0.1) # Percentile 10 of data
Error in quantile.default(as.vector(exp.matrix), 0.1) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
```

**Comment by AngelCampos** [comment]
Hello. Pathifier is not my software, the code here serves to load data into Pathifier using the parameters used in the Domany lab and making graphs of the results. I made it while I was visiting the lab in 2016. Pathifier is in bioconductor, for citing information follow this [link](https://bioconductor.org/packages/release/bioc/html/pathifier.html).

The error you are getting is because there are NAs in your data. You can change the line 
`min_exp <- quantile(as.vector(exp.matrix), 0.1) # Percentile 10 of data`
for 
`min_exp <- quantile(as.vector(exp.matrix), 0.1, na.rm = TRUE) # Percentile 10 of data`

And then it should proceed. But in general, is good to figure out why there are NA values instead of zeros when there were no reads for said genes.

If you use my code, please consider citing it as: Angel García-Campos. (2018, March 17). AngelCampos/Pathifier-Tool-Kit: v1.0 (Version pathifierTools_v1.0). Zenodo. http://doi.org/10.5281/zenodo.1202186

I'm not sure of appending that line to the code as it is sometimes better to find out that there are NAs in the data. And clean it accordingly.

Hope this solves your issue
Best

**Comment by beginner984** [comment]
Hello

I have log2 transformed normalized values from DESeq2 by log2(data+1)

I have stored my data in a R object

I have tried your code, but I get this error

```
> PDS<-quantify_pathways_deregulation(exp.matrix1, d, kegg$gs, kegg$pathwaynames,normals, attempts = 100,                                     min_exp=1, min_std=0.575) robust_score_bydist. min_exp= 1 , min_std= 0.575 Error in if (var(t) > 0) { : missing value where TRUE/FALSE needed

In addition: Warning message:In if (var(t) > 0) { :  the condition has length > 1 and only the first element will be used
```

Could you please look at my R object to see where I do wrong?

This is my R object here

https://www.dropbox.com/s/ioun24t3iu0hsjx/Pathifier.RData?dl=0

**Comment by AngelCampos** [comment]
Hello beginner984. Your data has NAs. I just removed them and plug the data you sent me into the code of the file `1_Run_Pathifier.R` and got the results attached in the zip file here, along with the adapted code.

[beginner984.zip](https://github.com/AngelCampos/Pathifier-Tool-Kit/files/5517310/beginner984.zip)

Hope this helps you run Pathifier in your data

If you use my code, please cite it as: Angel García-Campos. (2018, March 17). AngelCampos/Pathifier-Tool-Kit: v1.0 (Version pathifierTools_v1.0). Zenodo. http://doi.org/10.5281/zenodo.1202186

Best

**Comment by beginner984** [comment]
Thank you so much to be this helpful

Of course I should and I would cite the mentioned reference

Thanks again

**Comment by AngelCampos** [comment]
No problem. Good luck.
